AWSTemplateFormatVersion: "2020-01-01"
Transform: AWS::Serverless-2016-10-31
Description: Offline test of badges_and_training
Resources:
  bgv_role:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: src/lambda/question/index.handler
      Timeout: 30
      Environment:
        Variables:
          AWS_REGION: local

      Events:
        AllProduct:
          Type: Api
          Properties:
            Path: /bgv_role
            Method: any

  bgv_permission:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: src/lambda/question/index.handler
      Timeout: 30
      Environment:
        Variables:
          AWS_REGION: local

      Events:
        AllProduct:
          Type: Api
          Properties:
            Path: /bgv_permission
            Method: any

